const { DataTypes, uuidPk, uuidCol, fk, defineModel } = require('./_schema');

module.exports = defineModel(
  'Touchpoint',
  'touchpoints',
  {
    id: uuidPk(),
    touchpoint_uuid: uuidCol(),
    contact_id: fk('contacts'),
    lead_id: fk('leads'),
    visitor_id: fk('visitors'),
    session_id: fk('sessions'),
    occurred_at: { type: DataTypes.DATE, allowNull: false, defaultValue: DataTypes.NOW },
    channel: { type: DataTypes.STRING, allowNull: true },
    source: { type: DataTypes.STRING, allowNull: true },
    medium: { type: DataTypes.STRING, allowNull: true },
    campaign: { type: DataTypes.STRING, allowNull: true },
    campaign_id: { type: DataTypes.STRING, allowNull: true },
    adset_id: { type: DataTypes.STRING, allowNull: true },
    ad_id: { type: DataTypes.STRING, allowNull: true },
    creative_id: { type: DataTypes.STRING, allowNull: true },
    utm_source: { type: DataTypes.STRING, allowNull: true },
    utm_medium: { type: DataTypes.STRING, allowNull: true },
    utm_campaign: { type: DataTypes.STRING, allowNull: true },
    utm_term: { type: DataTypes.STRING, allowNull: true },
    utm_content: { type: DataTypes.STRING, allowNull: true },
    gclid: { type: DataTypes.STRING, allowNull: true },
    gbraid: { type: DataTypes.STRING, allowNull: true },
    wbraid: { type: DataTypes.STRING, allowNull: true },
    fbclid: { type: DataTypes.STRING, allowNull: true },
    landing_page: { type: DataTypes.STRING, allowNull: true },
    landing_page_variant: { type: DataTypes.STRING, allowNull: true },
    metadata: { type: DataTypes.JSON, allowNull: true },
  },
  {
    indexes: [
      { unique: true, fields: ['touchpoint_uuid'] },
      { fields: ['contact_id'] },
      { fields: ['lead_id'] },
      { fields: ['visitor_id'] },
      { fields: ['session_id'] },
      { fields: ['gclid'] },
      { fields: ['fbclid'] },
      { fields: ['occurred_at'] },
    ],
  }
);
